server:
  port: 80
management:
  server:
    port: 9090
  endpoint:
    shutdown:
      enabled: true # 可以直接进行远程关闭
    health:
      show-details: always # 显示异常信息
      show-components: always # 显示组件信息
  endpoints:
    web:
      exposure:
        include: "*" # 开放全部的微服务监控端口
      base-path: /actuator # 监控服务的父路径

info:
  app:
    name: 沐言科技 —— SpringBoot微服务
    group: com.yootk
    version: 2.4.3
    describe: 基于SpringBoot实现了微服务的定义，用于实现XXOO功能
    creator:
      name: 李兴华
      poistion: 教学总监