server:
  port: 80
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: "*" # 开放全部的微服务监控端口
      base-path: /actuator # 监控服务的父路径

info:
  app:
    name: 沐言科技 —— SpringBoot微服务
    group: com.yootk
    version: 2.4.3
    describe: 基于SpringBoot实现了微服务的定义，用于实现XXOO功能
    creator:
      name: 李兴华
      poistion: 教学总监
logging:
  level: # 需要配置Map集合
    root: info # 基本的日志级别
spring:
  profiles:
    active: env
  redis:
    host: 192.168.190.130 # Redis主机地址
    port: 6379 # Redis端口
    password: hello # 密码
    database: 0 # 第0个数据库
    connect-timeout: 200
    timeout: 200
    lettuce: # 使用Lettuce连接池
      pool:
        max-active: 100
        max-idle: 20
        min-idle: 10
        max-wait: 1000
        time-between-eviction-runs: 2000 # 每2秒回收一次空闲连接
