object: # 配置的前缀
  deptno: 10
  dname: 教学研发部
  company: # 关联的其他类的引用
    cid: 1009
    cname: 沐言科技
  emps[0]:
    empno: 7369
    ename: Smith
    job: 办事员
  emps[1]:
    empno: 7566
    ename: Allen
    job: 部门经理
  emps[2]:
    empno: 7839
    ename: king
    job: 董事长