spring:
  application:
    name: microboot-jwt # 应用名称
muyan: # 自定义配置项
  config: # 配置项定义
    jwt: # 配置JWT相关属性
      sign: muyan # JWT证书签名
      issuer: MuyanYootk # 证书签发人
      secret: www.yootk.com # 加密密钥
      expire: 10000 # 有效时间（单位：秒）