server:
  port: 80
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springsecurity
    username: root
    password: mysqladmin
  jpa:
    show-sql: true
    properties:
      hibernate: # 添加JPA的属性
        enable_lazy_load_no_trans: true # 配置延迟加载